### PR TITLE
Add test execution times and a timeout of 600s

### PR DESCRIPTION
**Pull request by jklaise**
Addresses #840.

This is primarily to see what is causing mac-os CI tests to periodically run to ~6h before getting killed.

### CODE REVIEW

**Comment by jklaise** [comment]
@ascillitoe I would advocate including the `--durations=50 --durations-min=1.0` flags by default for `alibi` and `alibi-detect`, whilst the `pytest-timeout` flag should be temporary in case we have frequently hanging tests like we've observed for `mac-os` on CI here. Otherwise the routine usage of `pytest-timeout` in a test suite is not particularly recommended, e.g. https://github.com/pytest-dev/pytest-timeout#thread (nevertheless, note that we currently do use it for notebook tests, the overhead hear would be minimal compared to the time it takes to execute the notebooks).

**Comment by ascillitoe** [comment]
@jklaise including the `--durations=50 --durations-min=1.0` by default makes sense to me, as does only using `pytest-timeout` temporarily given the large number of tests we set-up/teardown.

Just to check, by `pytest-timeout` being temporary does that mean you will be commenting it out once the CI has run (before merge)?

**Comment by ascillitoe** [comment]
p.s. just noticed you didn't include `pytest-timeout` in https://github.com/SeldonIO/alibi-detect/pull/712/files. Maybe it makes sense to include it but have it commented out with a note saying when it should be uncommented?

**Comment by jklaise** [comment]
@ascillitoe it seems I might have to merge this to `master` to investigate the mac-os failing as we seem unable to replicate it on regular PRs, but generally yes, the `pytest-timout` shouldn't be used routinely.

I didn't include it for `alibi-detect` on purpose as we haven't seen any similar failings there (it's also unwieldy, as for the whole CI to pass need to add to all the `tox` environments too.

**Comment by ascillitoe** [comment]
Ah I didn't consider `tox`. Makes sense to leave out in general then!

**Pull request merged**
