### PR TITLE
Bug fix: Include forward_args in self.model function calls in intergrated_gradients.py

### PR DESCRIPTION
**Pull request by sanjass**
Bug report + fix: `forward_kwargs` not used in all `self.model` calls in `integrated_gradients.py`
https://github.com/SeldonIO/alibi/issues/524

### CODE REVIEW

**Comment by jklaise** [comment]
@sanjass the tests are failing because we also pass in `forward_kwargs` when it is `None`. We would need to add the same logic to these calls as here: https://github.com/SeldonIO/alibi/blob/610013595ad2da40286a22ebca03bd5b5ffe25e4/alibi/explainers/integrated_gradients.py#L143-L146

Given the repetition I think it would be good to split this out into a small utility function (or actually, would be good to check if we could just substitute `None` for the empty dictionary `{}` and it might run without having to do this check).

**Comment by sanjass** [comment]
I see, I pushed a change as follows:
```
if forward_kwargs is None:
    forward_kwargs = {}
```
and replaced `If forward_kwargs is not None`-> `if forward_kwargs`
also removed `if forward_kwargs is None` and passed `**forward_kwargs` as before

Didn't get to run the checks though

**Comment by jklaise** [comment]
Thanks! Changes look good, I will rerun the IG notebooks (especially the transformers one) before merging.

**Comment by jklaise** [comment]
@sanjass just a recommendation, if you also do `pip install -r requirements/dev.txt` and run `flake8 alibi` from the repo source you can see all the linting errors and fix them locally :)

**Comment by sanjass** [comment]
Yeah, did something like that but my previous fix introduced a different flake8 error and I didn't double check lol. Also I'm editing in the github editor directly. Anyways hopefully this finally works

**Comment by RobertSamoilescu** [comment]
@sanjass we will be working on issue #527 before merging this PR.

**Review by jklaise — APPROVED** [review]

**Comment by jklaise** [comment]
@sanjass thank you for your contribution! And thanks for the extra review @RobertSamoilescu!

**Pull request merged**
