### PR TITLE
Changed keras reference to v1 compatibility module

### PR DESCRIPTION
**Pull request by jimbudarz**
Quick fix for issue #388

### CODE REVIEW

**Comment by jimbudarz** [comment]
I saw errors in testing around Integrated Gradients, but they already existed on the branch without these changes.

**Comment by jklaise** [comment]
Thanks! What errors did you see locally?

**Comment by jimbudarz** [comment]
@jklaise They were all like this:
```
_______________________________________ test_integrated_gradients_regression[1-riemann_middle-ffn_model0] _______________________________________
Traceback (most recent call last):
  File "/home/username/github/alibi/alibi/explainers/tests/test_integrated_gradients.py", line 452, in test_integrated_gradients_regression
    target=None)
  File "/home/username/github/alibi/alibi/explainers/integrated_gradients.py", line 508, in explain
    nb_samples)
  File "/home/username/github/alibi/alibi/explainers/integrated_gradients.py", line 627, in _compute_attributions_list_input
    for path in paths_ds:
  File "/home/username/venvs/alibi/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2776, in __iter__
    return iter(self._dataset)
  File "/home/username/venvs/alibi/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 424, in __iter__
    raise RuntimeError("__iter__() is only supported inside of tf.function "
RuntimeError: __iter__() is only supported inside of tf.function or when eager execution is enabled.
--------------------------------------------------------------- Captured log call ---------------------------------------------------------------
WARNING  alibi.explainers.integrated_gradients:integrated_gradients.py:466 It looks like you are passing a model with a scalar output and target is set to `None`.If your model is a regression model this will produce correct attributions. If your model is a classification model, targets for each datapoint must be defined. Not defining the target may lead to incorrect values for the attributions.Targets can be either the true classes or the classes predicted by the model.
```

**Comment by jklaise** [comment]
Ahh, this is because we actually need to run pytest in two passes due to having some tensorflow 1.x code in the codebase which needs eager mode switched off, but once you do that there is no way back. It's in our CI script here: https://github.com/SeldonIO/alibi/blob/658d7772d63685ec9634a0dbc50f39fcc89b093f/.github/workflows/ci.yml#L50-L51 I'll update the contributing.md file to reflect this.

**Pull request merged**
